### ISSUE TITLE
open source checklist

### ISSUE THREAD

**Issue by sleitner** [sleitner/new-relic-installer#1]
- [x] **Has PII been removed?**
  - Use [Clouseau](https://github.com/virtix/clouseau) for scanning source code.
  - If there are images, visually inspect each image to ensure there is no CFPB-specific information.
- [ ] **Have security vulnerabilities been remediated?**
- [x] **Are we including any other open source products? If so, is there any conflict with our public domain release?**
- [x] **Is our `TERMS.md` included?**
- [ ] **Is a `CHANGELOG.md` present and does it contain structured, consistently formatted recent history?**
- [x] **Are instructions for contributing included (`CONTRIBUTING.md`)?**
- [x] **Are installation instructions clearly written in the `README` _and_ tested on a clean machine?**
- [ ] **Are all dependencies described in the `README`, `requirements.txt`, and/or `buildout.cfg`?**
- [ ] **Are the API docs generated?**
- [ ] **Are there unit tests?**
- [x] **If applicable and possible, is it set up in TravisCI?**
- [ ] **Have multiple people reviewed the code?**
- [x] **Is there a screenshot in the `README`, if applicable?**
